spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mvt_096
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

web:
  kztLink: https://api.twelvedata.com/time_series?symbol=USD/KZT&interval=1day&outputsize=5&apikey=${web.apiKey}
  rubLink: https://api.twelvedata.com/time_series?symbol=USD/RUB&interval=1day&outputsize=5&apikey=${web.apiKey}
  apiKey: d1615d72e26a4f17bdc4b394ff483492

cron:
  expression: '0 0 0 * * MON-FRI'