spring:
  datasource:
    url: jdbc:postgresql://localhost:${settings.databasePort}/${settings.databaseName}
    driver-class-name: org.postgresql.Driver
    username: ${settings.databaseUsername}
    password: ${settings.databasePassword}
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:${settings.databasePort}/${settings.databaseName}
    user: ${settings.databaseUsername}
    password: ${settings.databasePassword}
    baseline-version: 1.0

web:
  kztLink: https://api.twelvedata.com/time_series?symbol=USD/KZT&interval=1day&outputsize=5&apikey=${web.apiKey}
  rubLink: https://api.twelvedata.com/time_series?symbol=USD/RUB&interval=1day&outputsize=5&apikey=${web.apiKey}
  apiKey: d1615d72e26a4f17bdc4b394ff483492

cron:
  currencySet: '0 0 0 * * MON-FRI'
  monthLimit: '0 0 0 1 * *'

settings:
  databasePort: # тут указать собственные настройки
  databaseName: # тут указать собственные настройки
  databaseUsername: # тут указать собственные настройки
  databasePassword: # тут указать собственные настройки
